swagger: "2.0"
info:
  version: "0.0.1"
  title: RENS Framework
# during dev, should point to your local machine
host: localhost:8325
# basePath prefixes all resource paths
basePath: /api/v1
#
schemes:
  # tip: remove http to make production-grade
  - http
  # - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /get/token/{id}:
    get:
      description: Returns json token
      parameters:
        - in: path
          name: id
          description: user id
          type: string
          required: true
      responses:
        "200":
          description: logged in user object returned
          schema:
            $ref: '#/definitions/SuccessResponse'
        "404":
          description: fetch user error
          schema:
            $ref: '#/definitions/ErrorResponse'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /auth/local/login:
    post:
      description: Returns user information
      parameters:
        - name: RequestBody
          in: body
          description: User's email required
          required: true
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        "201":
          description: logged in user object returned
          schema:
            $ref: '#/definitions/SuccessResponse'
        "400":
          description: Wrong password for that user
          schema:
            $ref: '#/definitions/ErrorResponse'
        "404":
          description: fetch user error
          schema:
            $ref: '#/definitions/ErrorResponse'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /auth/local/logout/{id}:
    get:
      description: Logouts user
      operationId: logout user by id
      parameters:
        - in: header
          description: Needed web token and user id
          name: Authorization
          required: true
          type: string
        - in: header
          description: Needed user id
          name: User
          required: true
          type: integer
          format: int64
        - name: id
          in: path
          description: ID of user to fetch
          required: true
          type: integer
          format: int64
      responses:
        "200":
          description: user logout response
          schema:
            $ref: '#/definitions/SuccessResponse'
        "403":
          description: Authorization user
          schema:
            $ref: '#/definitions/ErrorResponse'
        "404":
          description: Authorization user
          schema:
            $ref: '#/definitions/ErrorResponse'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /auth/local/register/visitor:
    post:
      description: Creates and returns user information
      parameters:
        - name: RequestBody
          in: body
          description: Creates visitor user permissions
          required: true
          schema:
            type: object
            required:
              - email
              - password
              - firstName
              - lastName
            properties:
              email:
                type: string
              password:
                type: string
              firstName:
                type: string
              lastName:
                type: string
      responses:
        "201":
          description: logged in user object returned
          schema:
            $ref: '#/definitions/SuccessResponse'
        "404":
          description: fetch user error
          schema:
            $ref: '#/definitions/ErrorResponse'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /auth/local/register/admin:
    post:
      description: Creates and returns user information
      parameters:
        - name: RequestBody
          in: body
          description: Creates admin user permissions
          required: true
          schema:
            type: object
            required:
              - email
              - password
              - firstName
              - lastName
            properties:
              email:
                type: string
              password:
                type: string
              firstName:
                type: string
              lastName:
                type: string
      responses:
        "201":
          description: logged in user object returned
          schema:
            $ref: '#/definitions/SuccessResponse'
        "404":
          description: fetch user error
          schema:
            $ref: '#/definitions/ErrorResponse'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /auth/local/register/guest:
    post:
      description: Creates and returns user information
      parameters:
        - name: RequestBody
          in: body
          description: Creates guest user permissions
          required: true
          schema:
            type: object
            required:
              - email
              - password
              - firstName
              - lastName
            properties:
              email:
                type: string
              password:
                type: string
              firstName:
                type: string
              lastName:
                type: string
      responses:
        "201":
          description: logged in user object returned
          schema:
            $ref: '#/definitions/SuccessResponse'
        "404":
          description: fetch user error
          schema:
            $ref: '#/definitions/ErrorResponse'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /auth/local/change/password/{id}:
    patch:
      description: Changes users password
      parameters:
        - in: header
          description: Needed web token and user id
          name: Authorization
          required: true
          type: string
        - in: header
          description: Needed user id
          name: User
          required: true
          type: integer
          format: int64
        - name: id
          in: path
          description: ID of user to fetch
          required: true
          type: integer
          format: int64
        - name: RequestBody
          in: body
          description: Creates guest user permissions
          required: true
          schema:
            type: object
            required:
              - newPassword
              - password
            properties:
              newPassword:
                type: string
              password:
                type: string
      responses:
        "202":
          description: logged in user object returned
          schema:
            $ref: '#/definitions/SuccessResponse'
        "400":
          description: wrong password
          schema:
            $ref: '#/definitions/ErrorResponse'
        "403":
          description: Authorization user
          schema:
            $ref: '#/definitions/ErrorResponse'
        "404":
          description: fetch user error
          schema:
            $ref: '#/definitions/ErrorResponse'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  SuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
